server:
  port: 18080

spring:
  application:
    name: post-bubi
  datasource:
    url: jdbc:h2:file:./data/post-bubi
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 120MB
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

post-bubi:
  version: '@project.version@'
  storage:
    files-dir: ./data/files
    protos-dir: ./data/protos
  bur:
    code-table-dir: ./data/CodeTable
